#!/usr/bin/env node
'use strict';

const meow = require('meow');
const fs = require('fs');
const concat = require('concat-stream');
const csv2geojson = require('./');

const cli = meow(
    `
Usage: ./csv2geojson --lat [string] --lon [string] --delimiter [string] FILE

Options:
  --lat             the name of the latitude column
  --lon             the name of the longitude column
  --line            whether or not to output points as a LineString       [default: false]
  --delimiter       the type of delimiter                                 [default: ","]
  --numeric-fields  comma separated list of fields to convert to numbers
`,
    {
        flags: {
            lat: {type: 'string'},
            lon: {type: 'string'},
            line: {type: 'boolean', default: false},
            delimiter: {type: 'string', default: ','},
            numericFields: {type: 'string'},
        },
    }
);

const file = cli.input[0];
const {lat, lon, delimiter, numericFields, line} = cli.flags;

if (process.stdin.isTTY && !file) return cli.showHelp();

const stream = file ? fs.createReadStream(file) : process.stdin;
stream.pipe(concat(convert));

function convert(data) {
    csv2geojson.csv2geojson(
        data.toString(),
        {latfield: lat, lonfield: lon, delimiter, numericFields},
        function (err, data) {
            if (err) console.error(JSON.stringify(err, null, 2));
            if (line) data = csv2geojson.toLine(data);
            console.log(JSON.stringify(data, null, 2));
        }
    );
}
